const url = require('url')
const address = 'http://www.koikoi.com.br/lojas/pinturas/paracolorir?tintas=rosa#orestoacabou'
const parseUrl = new url.URL(address)
console.log(parseUrl)
console.log(parseUrl.protocol)
console.log(parseUrl.hostname)
console.log(parseUrl.pathname)
console.log(parseUrl.search)
console.log(parseUrl.searchParams)
console.log(parseUrl.hash)